repos:
- hooks:
  - args:
    - --profile
    - black
    - src/
    entry: isort
    id: isort
    name: isort
    types:
    - python
  repo: https://github.com/pycqa/isort
  rev: 5.12.0
- hooks:
  - args:
    - src/
    entry: black
    id: black
    name: black
    types:
    - python
  repo: https://github.com/ambv/black
  rev: 22.12.0
- hooks:
  - args:
    - src/
    entry: flake8
    id: flake8
    name: flake8
    types:
    - python
  repo: https://github.com/pycqa/flake8
  rev: 5.0.4
- hooks:
  - entry: nbstripout
    id: nbstripout
    name: nbstripout
  repo: https://github.com/kynan/nbstripout
  rev: 0.6.1
- hooks:
  - id: commitizen
  repo: https://github.com/commitizen-tools/commitizen
  rev: v3.13.0
